# Generated by Django 5.0.3 on 2024-04-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
